// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

var fibonacci = function(){
  var numbers = [];
  var result = 0;

  for(var i=0; i<35; i++){
    if(i<2){
      numbers.push(i);
    } else {
      var newNum = numbers[i-1] + numbers[i-2]
      if(newNum > 4000000){
        break;
      }
      if(newNum%2 === 0){
        result += newNum;
      }
      numbers.push(newNum);
    }
  }
  return result;
};